// flaticon.com

export const Data=[
    {
        uri:require('../../images/prayer-mat.png'),
        title:'Prayer Times',
        id:'123456',
        screenName:'SalahTimes'
    },
    {
        uri:require('../../images/compass.png'),
        title:'Qibla',
        id:'123457',
        screenName:'QiblaNavigator'
    },
    {
        uri:require('../../images/dua.png'),
        title:'Dua',
        id:'123458',
        screenName:''
    },
    {
        uri:require('../../images/tasbih.png'),
        title:'Tasbih',
        id:'123459',
        screenName:''
    },
    {
        uri:require('../../images/quran.png'),
        title:'Quran',
        id:'123450',
        screenName:'Quran'
    },
    {
        uri:require('../../images/teaching.png'),
        title:'Teachings',
        id:'123466',
        screenName:''
    },
    {
        uri:require('../../images/dictionary.png'),
        title:'Dictionary1',
        id:'123476',
        screenName:'Dummy'
    },
    {
        uri:require('../../images/dictionary.png'),
        title:'Tracker',
        id:'123486',
        screenName:'TabNavigatorTracker'
    },
    {
        uri:require('../../images/dictionary.png'),
        title:'Dictionary',
        id:'123496',
        screenName:''
    },
    {
        uri:require('../../images/dictionary.png'),
        title:'Dictionary',
        id:'123406',
        screenName:''
    },
];

